name: Nightly Test

# Run the nightly tests at at 6 AM UTC
on:
  schedule:
    - cron: "0 6 * * *"
jobs:

  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        arch: [linux/amd64, linux/arm64]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build
        uses: docker/build-push-action@v2
        with:
          platforms: ${{ matrix.arch }}
          context: ./build
          file: ./Dockerfile
          push: false
          load: true
          tags: oittaa/imagemagick:latest
          build-args: |
            CI=true
      - name: Tests
        run: PLATFORM="${{ matrix.arch }}" ./test.sh

  dependencies:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Update Dependencies
        run: ./update-dependencies.sh
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3.8.2
