name: Nightly Test

# Run the nightly tests at at 6 AM UTC
on:
  schedule:
    - cron: "0 6 * * *"
jobs:

  build-amd64:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build AMD64
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64
          context: ./build
          file: ./Dockerfile  
          push: false
          load: true
          tags: oittaa/imagemagick:latest
      - name: Tests
        run: ./test.sh

  build-arm64:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build ARM64
        uses: docker/build-push-action@v2
        with:
          platforms: linux/arm64
          context: ./build
          file: ./Dockerfile
          push: false
          load: true
          tags: oittaa/imagemagick:latest
      - name: Tests
        run: ./test.sh
