name: Nightly Test

# Run the nightly tests at at 6 AM UTC
on:
  schedule:
    - cron: "0 6 * * *"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        arch: [linux/amd64, linux/arm64]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: Update Dependencies
        run: ./update-dependencies.sh
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.2.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.7.1
      - name: Build
        uses: docker/build-push-action@v6.9.0
        with:
          platforms: ${{ matrix.arch }}
          context: ./build
          file: ./build/Dockerfile
          push: false
          load: true
          tags: oittaa/imagemagick:latest
      - name: Tests
        run: |
          cp -a test test-backup
          PLATFORM="${{ matrix.arch }}" ./test.sh
          ls -l test && rm -rf test && mv test-backup test
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          delete-branch: true
          title: 'Update dependencies by create-pull-request action'
